language: php

php:
  - 7.1
  - 7.2
  - 7.3

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: SYMFONY_VERSION='3.4.*'
    - php: 7.2
      env: SYMFONY_VERSION='4.1.*'
    - php: 7.2
      env: SYMFONY_VERSION='4.2.*'

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi

install: composer update $COMPOSER_FLAGS --prefer-dist

script: if [[ "$TRAVIS_PHP_VERSION" == "7.1" && -z "$SYMFONY_VERSION" && -z "$COMPOSER_FLAGS" ]]; then bin/phpunit --coverage-clover=coverage.clover; else bin/phpunit; fi

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - if [ -f coverage.clover ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
