language: php

php:
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: hhvm-3.12
  fast_finish: true
  include:
    - php: 5.6
      env: SYMFONY_VERSION='2.7.*'
    - php: 5.6
      env: COMPOSER_FLAGS='--prefer-lowest'
    - php: 5.6
      env: SYMFONY_VERSION='2.8.*'
    - php: 7.0
      env: SYMFONY_VERSION='2.8.*'
    - php: hhvm-3.12
      sudo: required
      dist: trusty
      group: edge

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi

install: composer update $COMPOSER_FLAGS --prefer-dist

script: if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover; else vendor/bin/phpunit; fi

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - if [ -f coverage.clover ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
